import pandas as pd
import pytest
from spotforecast2_safe.data.data import Period
from spotforecast2_safe.preprocessing.exog_builder import ExogBuilder

def test_exog_builder_build_example():
    """
    Test the ExogBuilder.build method based on its docstring example.
    
    Safety Critical: Ensures that exogenous features are correctly generated 
    for a given date range with seasonal encoding, supporting robust model 
    inputs in high-stakes forecasting.
    """
    # 1. Define periods for seasonal encoding
    periods = [
        Period(name="hour", n_periods=24, column="hour", input_range=(0, 23))
    ]
    
    # 2. Initialize builder with German holidays and specified periods
    builder = ExogBuilder(periods=periods, country_code="DE")
    
    # 3. Define the evaluation window
    # Note: build() uses pd.date_range with default parameters, 
    # resulting in hourly steps from start to end inclusive.
    start = pd.Timestamp("2025-01-01", tz="UTC")
    end = pd.Timestamp("2025-01-02", tz="UTC")
    
    # 4. Execute the build process
    exog = builder.build(start, end)
    
    # 5. Safety-critical validations
    # Verify non-empty feature set
    assert exog.shape[1] > 0, "No features were generated by ExogBuilder"
    
    # Verify expected entries (25 hourly steps from 00:00 01-01 to 00:00 01-02)
    assert len(exog) == 25, f"Expected 25 rows, but got {len(exog)}"
    
    # Verify specific feature columns exist
    expected_cols = ["hour_0", "hour_23", "holidays", "is_weekend"]
    for col in expected_cols:
        assert col in exog.columns, f"Expected column '{col}' missing from final features"
        
    # Verify data integrity: 2025-01-01 is a holiday in DE (Neujahr)
    assert exog.loc[start, "holidays"] == 1, "2025-01-01 should be marked as a holiday"
    
    # Verify data integrity: 2025-01-01 is a Wednesday (2), 2025-01-02 is Thursday (3)
    # is_weekend should be 0 for both
    assert exog.loc[start, "is_weekend"] == 0
    assert exog.loc[end, "is_weekend"] == 0
